### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by ghost** [bsh-devsolutions/libs.validation.ts#1]
TypeError: Cannot read properties of undefined (reading 'call')
    at item.set (validator.js:75:80)
    at validator.js:317:25
    at Array.forEach (<anonymous>)
    at Validator.import (validator.js:310:68)
---
```json
{
    "items": [
        {
            "field": "name",
            "message": "This field is required!",
            "valid": false
        },
        {
            "field": "email",
            "message": "This field is required!",
            "valid": false
        }
    ]
}
```

**Comment by hamza-bousalih** [comment]
The error occurs because the validator attempts to set new values from the provided object into the object being validated, but the method responsible for retrieving the object is returning `undefined`. This leads to the failure when trying to update the values.

## Solution

To fix this issue, you need to call the `.init()` method on the validator. The `.init()` method should be used to pass a function that will return the object you want to validate. This is especially important when you intend to import validation results from another validator or application.

### Example Code

```typescript
import { BshValidationError, v } from "@bshg/validation";

v.configure({
  validatorOptions: {
    dev: true
  }
});

type User = {
  email: string;
  name: string;
};

const validator1 = v.validator<User>({
  id: "user-1-validator",
  items: {
    email: v.string().required().email(),
    name: v.string().required()
  }
});

const validator2 = v.validator<User>({
  id: "user-2-validator",
  items: {
    email: v.string().required().email(),
    name: v.string().required()
  }
})
  .init(() => ({
    email: "",
    name: ""
  }));

validator1.validateThrowAsync({
  email: "email",
  name: "1234"
})
  .then(() => console.log("pass"))
  .catch(v => {
    const error = v as BshValidationError;
    validator2.import(error.results); // This will works now
  });
```
- **`.init()` Method**: This method is crucial when you want to import the validation results into another validator, especially if you need to update the validated object's values with new values. This situation often arises when validation results are retrieved from an external source, such as a backend application. If you don't call `.init()` with the appropriate function, the validator may ignore the new values, potentially causing data loss.

**Comment by hamza-bousalih** [comment]
With the latest updates, you may encounter a warning like this:

`if the value of 'email' was changed, the new value will be ignored! to avoid this behavior, please use the '.init()' method to pass the object to set the changes to.`

![Warning Image](https://github.com/user-attachments/assets/da469e7a-615a-4497-ab81-d35455b36dad)
